CREATE TABLE [dbo].[Member]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Username] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(88) NOT NULL,
	[PhoneNumber] NVARCHAR(30) NULL,
	[Gender] NVARCHAR(10) NULL,
	[Address] NVARCHAR(500) NULL,
	[Salary] DECIMAL NOT NULL,
	[Permission] INT NOT NULL DEFAULT 0,
	[BankAccount] NVARCHAR(200) NOT NULL,
	[IsInProbation] BIT NOT NULL DEFAULT 1,
	[IsResigned] BIT NOT NULL DEFAULT 0,
	[Department] NVARCHAR(200) NULL,
	[DepartmentId] INT NULL,
	[Remark] NVARCHAR(500),
	[TeamId] INT NOT NULL,
	[PositionId] INT NULL,
	[JobGrade] INT NOT NULL DEFAULT 6,
	[WorkLocationId] INT NOT NULL,
	[IsSupervisor] BIT DEFAULT 0,
	[JoinDate] DATETIME DEFAULT GETDATE(),
	[IsAlertProbation] BIT DEFAULT 0,
	[IsDeleted] BIT DEFAULT 0,
	[BankName] NVARCHAR(200) NULL,
	[Position] NVARCHAR(200) NULL,
	[EmployeeId] NVARCHAR(200) NULL, 
	[IsTestUser] BIT DEFAULT 0,
    [IsFirstTimeUser] BIT NOT NULL DEFAULT 0,
	[Birthday] DATETIME NULL,
	[NationalId] NVARCHAR(200) NULL,
	[VehicleType] NVARCHAR(200) NULL,
	[VehicleNumber] NVARCHAR(200) NULL,
	[IsManager] BIT DEFAULT 0,
	[IsCanSeeMemberSalary] BIT DEFAULT 0
)
