CREATE PROCEDURE [dbo].[HRMS_IsMemberExist.1.0.0]
	@id int
AS
BEGIN
	SET NOCOUNT ON;
	IF EXISTS(SELECT TOP 1 1 FROM [dbo].[Member] WITH(NOLOCK) WHERE Id = @id)
	BEGIN
		SELECT 1;
	END
	ELSE
	BEGIN
		SELECT 0;
	END
END
GO