SELECT TOP (1000) [Id]
      ,[MemberId]
      ,[TransferTypeId]
      ,[DateCount]
      ,[Amount]
      ,[Remark]
      ,[PayDate]
      ,[CreatedBy]
      ,[CreatedOn]
      ,[ModifiedBy]
      ,[ModifiedOn]
  FROM [HRMSDB].[dbo].[Transfer]